import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import React from "react";
import { Poppins } from "next/font/google";
import { HeaderElement } from "@&/header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});
const PoppinsFont = Poppins({
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    variable: "--font-poppins",
    fallback: ["--font-sans"],
    display: "swap",
    subsets: ["latin", "latin-ext"],
    preload: true,
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {


    const CopyFn = async () => {
        "use server";
        const year = new Date().getFullYear();

        return <>&copy; {year} - Zota0</>
    }

    const Copy: React.FC = React.memo(() => <CopyFn />);
    Copy.displayName = "Copyright"

    return (
        <html lang="pl">
            <body
                className={`${PoppinsFont.variable} ${geistSans.variable} ${geistMono.variable} antialiased text-center font-[family-name:var(--font-geist-sans)]`}
            >
                <header className="w-full h-16 fixed bg-slate-700 top-0 left-0"><HeaderElement /></header>
                <main className="w-full min-h-svh bg-slate-900 text-left pt-32">
                    {children}
                </main>
                <footer className="w-full h-12 bg-slate-950"><Copy/></footer>
            </body>
        </html>
    );
}
