FROM golang-1.23.3 as go

WORKDIR working

COPY . /working

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main .

FROM alpine:latest

WORKDIR /app

COPY --from=go /working/main .

CMD ["./main"]